import genro_asgi


def test_version():
    assert genro_asgi.__version__ == "0.21.0"


def test_root_exports_public_api():
    expected = [
        "ASGIApp",
        "ApiKeyStore",
        "ApplicationGrammar",
        "AsgiConfigBuilder",
        "AsgiDbHandlerBase",
        "AsgiServer",
        "AsgiServerGrammar",
        "AuthCore",
        "AuthMethod",
        "AuthMixin",
        "AuthSection",
        "Avatar",
        "BaseApplication",
        "BaseMiddleware",
        "BaseServer",
        "ChannelClient",
        "CommunicationMixin",
        "ConfigError",
        "ConfigurationHandler",
        "FileApiKeyStore",
        "FileSessionStore",
        "FileUserStore",
        "Frame",
        "FrameStream",
        "HTTPBadRequest",
        "HTTPException",
        "HTTPForbidden",
        "HTTPNotFound",
        "HTTPUnauthorized",
        "LocalStorage",
        "LocalStorageNode",
        "McpApplication",
        "McpEngine",
        "McpError",
        "McpOpenApiApplication",
        "Message",
        "MemorySessionStore",
        "MiddlewareMixin",
        "OidcMethod",
        "OpenAPIPlugin",
        "OpenAPITranslator",
        "OpenApiApplication",
        "PasswordMethod",
        "PluginMixin",
        "Receive",
        "Redirect",
        "RegisteredRequest",
        "Request",
        "RequestRegistry",
        "Response",
        "RoutedApplication",
        "Scope",
        "Send",
        "ServerApplication",
        "Session",
        "SessionMixin",
        "SessionStore",
        "StorageMixin",
        "StorageNode",
        "TaskGrammar",
        "UserStore",
        "__version__",
        "router_openapi",
    ]
    assert genro_asgi.__all__ == expected
    for name in expected:
        assert hasattr(genro_asgi, name)
